// Generated by `cargo run -p vendor`. Do not edit manually.
//
//! The icon families compiled into this build.
//!
//! Each family is gated behind its Cargo feature, so a build only pays for
//! the fonts it asked for: a disabled family's assets are never embedded.

use crate::Family;

/// [Lucide](https://lucide.dev/icons) — ISC.
#[cfg(feature = "lucide")]
pub(crate) const LUCIDE: Family = Family {
    id: "lucide",
    label: "Lucide",
    feature: "lucide",
    font_family: "lucide",
    file_stem: "lucide",
    browse_url: "https://lucide.dev/icons",
    license: "ISC",
    font: include_bytes!("../assets/lucide/lucide.ttf"),
    index: include_str!("../assets/lucide/icons.idx"),
};

/// [Bootstrap Icons](https://icons.getbootstrap.com) — MIT.
///
/// Bootstrap publishes WOFF and WOFF2 only. The vendored .ttf is decoded
/// from the WOFF build at vendoring time; the glyph outlines are unchanged.
#[cfg(feature = "bootstrap")]
pub(crate) const BOOTSTRAP: Family = Family {
    id: "bootstrap",
    label: "Bootstrap Icons",
    feature: "bootstrap",
    font_family: "bootstrap-icons",
    file_stem: "bootstrap-icons",
    browse_url: "https://icons.getbootstrap.com",
    license: "MIT",
    font: include_bytes!("../assets/bootstrap/bootstrap-icons.ttf"),
    index: include_str!("../assets/bootstrap/icons.idx"),
};

/// [VS Code Codicons](https://microsoft.github.io/vscode-codicons/dist/codicon.html) — CC-BY-4.0.
///
/// Several names are aliases that share a codepoint; all are kept.
#[cfg(feature = "codicon")]
pub(crate) const CODICON: Family = Family {
    id: "codicon",
    label: "VS Code Codicons",
    feature: "codicon",
    font_family: "codicon",
    file_stem: "codicon",
    browse_url: "https://microsoft.github.io/vscode-codicons/dist/codicon.html",
    license: "CC-BY-4.0",
    font: include_bytes!("../assets/codicon/codicon.ttf"),
    index: include_str!("../assets/codicon/icons.idx"),
};

/// [Devicon](https://devicon.dev) — MIT.
///
/// Devicon's multi-colour 'original' variants exist only as SVG. The font
/// carries the single-colour plain/line variants.
#[cfg(feature = "devicon")]
pub(crate) const DEVICON: Family = Family {
    id: "devicon",
    label: "Devicon",
    feature: "devicon",
    font_family: "devicon",
    file_stem: "devicon",
    browse_url: "https://devicon.dev",
    license: "MIT",
    font: include_bytes!("../assets/devicon/devicon.ttf"),
    index: include_str!("../assets/devicon/icons.idx"),
};

/// [Font Awesome Free (Solid)](https://fontawesome.com/icons/packs/classic) — CC-BY-4.0 (icons), OFL-1.1 (fonts).
///
/// Upstream names both the solid and regular faces "Font Awesome 7 Free",
/// separating them only by weight. Each subset is renamed so it can be
/// addressed unambiguously by family.
#[cfg(feature = "fontawesome")]
pub(crate) const FA_SOLID: Family = Family {
    id: "fa-solid",
    label: "Font Awesome Free (Solid)",
    feature: "fontawesome",
    font_family: "fa-solid",
    file_stem: "fa-solid-900",
    browse_url: "https://fontawesome.com/icons/packs/classic",
    license: "CC-BY-4.0 (icons), OFL-1.1 (fonts)",
    font: include_bytes!("../assets/fa-solid/fa-solid-900.ttf"),
    index: include_str!("../assets/fa-solid/icons.idx"),
};

/// [Font Awesome Free (Regular)](https://fontawesome.com/icons/packs/classic) — CC-BY-4.0 (icons), OFL-1.1 (fonts).
#[cfg(feature = "fontawesome")]
pub(crate) const FA_REGULAR: Family = Family {
    id: "fa-regular",
    label: "Font Awesome Free (Regular)",
    feature: "fontawesome",
    font_family: "fa-regular",
    file_stem: "fa-regular-400",
    browse_url: "https://fontawesome.com/icons/packs/classic",
    license: "CC-BY-4.0 (icons), OFL-1.1 (fonts)",
    font: include_bytes!("../assets/fa-regular/fa-regular-400.ttf"),
    index: include_str!("../assets/fa-regular/icons.idx"),
};

/// [Font Awesome Free (Brands)](https://fontawesome.com/icons/packs/classic) — CC-BY-4.0 (icons), OFL-1.1 (fonts).
///
/// Brand marks are trademarks of their owners. Font Awesome's license does
/// not grant any right to use them.
#[cfg(feature = "fontawesome")]
pub(crate) const FA_BRANDS: Family = Family {
    id: "fa-brands",
    label: "Font Awesome Free (Brands)",
    feature: "fontawesome",
    font_family: "fa-brands",
    file_stem: "fa-brands-400",
    browse_url: "https://fontawesome.com/icons/packs/classic",
    license: "CC-BY-4.0 (icons), OFL-1.1 (fonts)",
    font: include_bytes!("../assets/fa-brands/fa-brands-400.ttf"),
    index: include_str!("../assets/fa-brands/icons.idx"),
};

/// [Nerd Fonts (Symbols Only)](https://www.nerdfonts.com/cheat-sheet) — MIT.
///
/// Symbols Nerd Font aggregates glyphs from many upstream sets, each under
/// its own license. Names keep their upstream prefix (cod-, dev-, fa-,
/// oct-, pom-, md-, weather-, and so on).
#[cfg(feature = "nerdfonts")]
pub(crate) const NERDFONTS: Family = Family {
    id: "nerdfonts",
    label: "Nerd Fonts (Symbols Only)",
    feature: "nerdfonts",
    font_family: "nerd-symbols",
    file_stem: "symbols-nerd-font",
    browse_url: "https://www.nerdfonts.com/cheat-sheet",
    license: "MIT",
    font: include_bytes!("../assets/nerdfonts/symbols-nerd-font.ttf"),
    index: include_str!("../assets/nerdfonts/icons.idx"),
};

/// [Octicons](https://primer.style/octicons) — MIT.
///
/// Taken from the Nerd Fonts `oct-` range rather than a Primer release:
/// Primer removed the icon font at Octicons v9 and publishes SVG only.
/// Names are normalised to Primer's spelling, so `arrow-down` rather than
/// the `oct-arrow_down` Nerd Fonts uses.
#[cfg(feature = "octicons")]
pub(crate) const OCTICONS: Family = Family {
    id: "octicons",
    label: "Octicons",
    feature: "octicons",
    font_family: "octicons",
    file_stem: "octicons",
    browse_url: "https://primer.style/octicons",
    license: "MIT",
    font: include_bytes!("../assets/octicons/octicons.ttf"),
    index: include_str!("../assets/octicons/icons.idx"),
};

/// [Pomicons](https://github.com/gabrielelana/pomicons) — See vendored LICENSE.
#[cfg(feature = "pomicons")]
pub(crate) const POMICONS: Family = Family {
    id: "pomicons",
    label: "Pomicons",
    feature: "pomicons",
    font_family: "pomicons",
    file_stem: "pomicons",
    browse_url: "https://github.com/gabrielelana/pomicons",
    license: "See vendored LICENSE",
    font: include_bytes!("../assets/pomicons/pomicons.ttf"),
    index: include_str!("../assets/pomicons/icons.idx"),
};

/// Every family enabled by the current feature set, in declaration order.
// Each push is behind its own `cfg`, so they cannot be collapsed into the
// initialiser the way the lint suggests.
#[allow(clippy::vec_init_then_push)]
pub(crate) fn enabled() -> Vec<&'static Family> {
    #[allow(unused_mut)]
    let mut families: Vec<&'static Family> = Vec::new();

    #[cfg(feature = "lucide")]
    families.push(&LUCIDE);
    #[cfg(feature = "bootstrap")]
    families.push(&BOOTSTRAP);
    #[cfg(feature = "codicon")]
    families.push(&CODICON);
    #[cfg(feature = "devicon")]
    families.push(&DEVICON);
    #[cfg(feature = "fontawesome")]
    families.push(&FA_SOLID);
    #[cfg(feature = "fontawesome")]
    families.push(&FA_REGULAR);
    #[cfg(feature = "fontawesome")]
    families.push(&FA_BRANDS);
    #[cfg(feature = "nerdfonts")]
    families.push(&NERDFONTS);
    #[cfg(feature = "octicons")]
    families.push(&OCTICONS);
    #[cfg(feature = "pomicons")]
    families.push(&POMICONS);

    families
}
